[package]
name = "banter_p2p"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.12.0"
actix-rt = "2.4.0"
base64 = "0.13.0"
bytes =  "1.1.0"
rand = "0.8.4"
tokio = { version = "1.13.0", features = ["full"] }
